line-length = 100

[format]
indent-style = "space"
quote-style = "double"

[lint]
select = ["E", "W", "F", "I", "N", "UP", "B", "C4", "RUF"]
ignore = [
    "B904",    # raise em except (padrão typer)
    "W291",    # Trailing whitespace SQL
    "W293",    # Whitespace em docstrings
    "E501",    # Linha muito longa
    "RUF022",  # __all__ não ordenado
]

[lint.isort]
known-first-party = ["timeblock"]
